### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by ann-james** [bkmgit/2023-06-20-aucenter-online#1]
Please update the links to the Tuesday/Wednesday website. I can't find the actual page that is currently online to update. Thanks!

**Comment by bkmgit** [comment]
Done. Changed:

- https://github.com/bkmgit/2023-06-20-aucenter-online/blob/gh-pages/index.md
- https://github.com/bkmgit/2023-06-20-aucenter-online/blob/gh-pages/_config.yml
- https://github.com/bkmgit/2023-06-20-aucenter-online/blob/gh-pages/_includes/lc/setup.html
- https://github.com/bkmgit/2023-06-20-aucenter-online/blob/gh-pages/_includes/lc/schedule.html
